<div class="card mb-4">
	<div class="card-header d-flex justify-content-between">
		<div>
			<b>Annotations</b>
		</div>
		<div>
			<a href="" class="btn btn-primary btn-rounded" data-bs-toggle="modal" data-target="#modalLoginForm">Add Annotation</a>
		</div>
	</div>
	<div class="card-body">
		<table class="table table-sm table-striped">
			<thead>
				<tr class="d-flex">
					<th class="col-2">User</th>
					<th class="col-8">Annotation</th>
					<th class="col-2">Date Created</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->annotations as $annotation) : ?>
				<?php echo sprintf('<tr class="d-flex"><td class="col">%s</td><td class="col">%s</td><td class="col">%s</td></tr>', $annotation['USER'], $annotation['ANNOTATION'], $annotation['DATE_CREATED']); ?>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>